### ISSUE TITLE
Geogebra Applets in spoilers are too wide

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#135]
by Hannes: Geogebra Applets in spoilers are wider than the page.

**Comment by inyono** [comment]
Update: this bug appears in solutions of exercises (among other cases I guess). For example, see the solution of the fourth exercises on https://de.serlo.org/mathe/sonstiges-testen/testaufgaben . Here the applet is too wide. But if you show only the solution directly, https://de.serlo.org/7083 , the applet displays correctly.

**Comment by inyono** [comment]
bump ^^': https://de.serlo.org/mathe/deutschland/bayern/gymnasium/vorbereitung-bmt-8/2016/gruppe-80454

**Comment by Knorrke** [comment]
should be better with new editor, because we're including geogebra applets via iframe there. Could change that in the old renderer too, though.
