### ISSUE TITLE
Zoom out On Smartphones

### ISSUE THREAD

**Issue by tinsaye** [serlo/athene2#179]
It would be very nice if one could zoom out on smartphones. I mean Smartphones now a days are big enough, so that you can read very well on them so why shouldn't I be able to zoom as I want. 
Here are just some reasons why:
PS: the third one is my favorite. And I think the last one is definitive a Bug.
![2015-08-10 14 02 33](https://cloud.githubusercontent.com/assets/5862858/9173440/60f55e8c-3f7a-11e5-80d2-e1b004ae6f2e.png)
![2015-08-10 14 03 01](https://cloud.githubusercontent.com/assets/5862858/9173437/60f3fe3e-3f7a-11e5-8eeb-40c5463eac29.png)
![2015-08-10 14 03 34](https://cloud.githubusercontent.com/assets/5862858/9173438/60f43732-3f7a-11e5-921a-941fb6debb60.png)
![2015-08-10 14 05 12](https://cloud.githubusercontent.com/assets/5862858/9173441/60f7a8e0-3f7a-11e5-85ab-4cf6ba28fe60.png)
![2015-08-10 14 05 22](https://cloud.githubusercontent.com/assets/5862858/9173439/60f4d26e-3f7a-11e5-8416-7affc53d3294.png)

Thank you!

**Comment by inyono** [comment]
Yeah, I also saw today, that the columns don't break, even on smartphone displays. Maybe we should reconsider this. Btw: I can zoom on iOS

**Comment by TinsayeAbye** [comment]
Really? I actually tried both Android and iOS

**Comment by inyono** [comment]
Oh, my bad. You meant to zoom **out**. That doesn't work, actually.

**Comment by TinsayeAbye** [comment]
Ok, yeah that's what i am talking about. Well can't we make the full size  a bit smaller, or a desktop version or give the clue to rotate the phone... 

The problem I see is actually : let say i introduce Serlo to some people or someone find our flyer: The first thing that most will do is probably search for it on there Smartphone ( well our home page looks very good which is pretty nice). But when someone take "Über Serlo" or "Mathematik" well in my opinion that wouldn't a professional impression.
PS: do we need the grey stripes on the side ( i mean on smartphones)

**Comment by kulla** [comment]
Issue is handled by redesign project and new editor
