### ISSUE TITLE
Geogebra applets on xs screens 

### ISSUE THREAD

**Issue by tinsaye** [serlo/athene2#183]
de.serlo.org/42091

The text-color gets brighter if there is a geogebra injection.

PS : Why does the applet disapears on Tablet mode?

**Comment by inyono** [comment]
The geogebra tube code injects some font-colors apparently...

Regarding the tablet mode: the applet will be hidden on small displays. For example, on my iPad it is shown in landscape mode, but not in portrait mode.

**Comment by TinsayeAbye** [comment]
Portrait mode: Is there any solution for that? i mean someone using half of his screen wouldn't see the applet

**Comment by inyono** [comment]
See #166 for text-color change

**Comment by kulla** [comment]
Implemented in new editor
