### ISSUE TITLE
Move informatics' taxonomy on de.serlo.org

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#280]
Currently, `/informatik` refers to the taxonomy. Rather, we want `/informatik` to be free for the homepage and instead `/informatik/` for the taxonomy, like it is done for math already.

**Comment by inyono** [comment]
ping @Knorrke

**Comment by Knorrke** [comment]
we now have `/informatik` for the landing page and `/informatik/themen` for the taxonomy
