### ISSUE TITLE
Review possible algebra APIs

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#307]
E.g.: algebra.js does not support `x` in denominator. This would be useful for derivation exercises (at least negative exponents for `x`...) Maybe, there are wolfram-alpha like APIs that we could use for free?

**Comment by inyono** [comment]
https://github.com/mathics/Mathics

**Comment by arekkas** [comment]
this is now more relevant as we're getting input back from people using input type exercises

**Comment by inyono** [comment]
* [ ] https://github.com/davidedc/Algebrite (looks like it has a good feature set. Division through x supported)
* [ ] https://github.com/aantthony/javascript-cas (has differentiation)

**Comment by Knorrke** [comment]
@inyono Is this implemented in the new editor?

**Comment by Knorrke** [comment]
we have a different library in the new editor now, which isn't perfect either but it got a nice code size and works for most use cases. Follow up is tracked in https://github.com/edtr-io/edtr-io/issues/270
