### ISSUE TITLE
Breadcrumbs fail on latest Chrome v49

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#378]
Only relevant for no longer supported OSs like Windows XP + Vista. Chrome won't longer update on these systems and is stuck in version 49. Somehow, Chrome renders the breadcrumbs in mobile view...

**Comment by Knorrke** [comment]
Same problem occurs on Windows 10, Chrome v53 and v54 (64-Bit version)

**Comment by Knorrke** [comment]
Only fails on some devices... somehow the height of the breadcrumbs change from device to device, not sure why.

**Comment by inyono** [comment]
Okay... Will have to refactors this, then...

**Comment by Knorrke** [comment]
XP and Vista are really out of date, so I'll close this as "won't fix".
