### ISSUE TITLE
Introduce ability to modify meta tags

### ISSUE THREAD

**Issue by aeneasr** [serlo/athene2#454]
Currently, meta tags are generated automatically by the Normalizer. We want to keep that as a fall back, but prioritize user input for them. We need to add meta tags to:

* [ ] Entities
* [ ] Pages
* [ ] Taxonomies

**Comment by elbotho** [comment]
maybe this could include a featured image tag that could be used for #436 :)

**Comment by arekkas** [comment]
partially resolved: articles

**Comment by kulla** [comment]
Implemented with Seo project
