### ISSUE TITLE
Geogebra applets are broken due to CSP

### ISSUE THREAD

**Issue by aeneasr** [serlo/athene2#475]
Refused to load the font 'about:blank' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-inline' 'unsafe-eval'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by arekkas** [comment]
I searched quite some while in the apach2 logs, obviously this is done on the varnish proxy...

**Comment by Knorrke** [comment]
@inyono not sure, but I think this is not an issue anymore?

**Comment by inyono** [comment]
error ist still occuring. Not sure tho, how it impacts us

**Comment by kulla** [comment]
Cannot reproduce the issue -> seems to be fixed
