### ISSUE TITLE
remove permission taxonomy.term.associate from login role

### ISSUE THREAD

**Issue by Knorrke** [serlo/athene2#486]
Currently every user has the permission taxonomy.term.associate, because it's needed to associate a new entity with the taxonomy. However with the same permission you can use batch-copy ~and batch-move~, so it's possible for every registered user to mess up i.e. the curriculum-taxonomy.

So far we discussed two solutions:
- remove the permission taxonomy.term.associate from login role and associate new entities automatically without checking for the permission. This would make sense because you don't want any situation were one can create an entity but not associate it in the taxonomy.
- add new permission for batch-copy/ -move

EDIT: batch move is not allowed with taxonomy.term.associate permission

**Comment by arekkas** [comment]
How about adding a permission for batch copy/move?

**Comment by Knorrke** [comment]
Closing, as batch move is not possible. Copy is not that big of a problem. Create a new issue in serlo/serlo.org if this is still an issue.
