### ISSUE TITLE
Prüfungsaufgaben

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2#498]
Um Prüfungsaufgaben abbilden zu können, soll es die Möglichkeit geben, den klassischen Textaufgaben weitere Lösungen hinzuzufügen. Dafür brauchen wir:

- Option von mehreren Lösungen in die Definition des Lernobjekts schreiben.
- Lösungen generell mit Titel versehen, der statt "Lösung anzeigen" ausgegeben wird . Ist der Titel leer (Standard bei den meisten Aufgaben), wird im User Interface weiterhin "Lösung anzeigen" ausgegeben. Bei der ausgeklappten Lösung ist und bleibt unabhängig von dem Titel "Lösung ausblenden" stehen.  
- Frontend für die Anzeige mehrerer Lösungen (untereinander reihen).

**Comment by SimonKoehl** [comment]
zu a) Allein zu vermitteln, in welchen Fällen genau das angewendet werden darf (Teillösungen, ok. Aber was ist mit alternativen Lösungen?). Des Weiteren haben Lösungen gerade noch keinen Titel. Wie hält man sie auseinander? Wenn sie einen Titel bekommen: Was machen wir dann mit dem, wenn es (wie bei 99% der Aufgabe) nur eine Lösung gibt? usw. ..

**Comment by Knorrke** [comment]
Das letztere ist in der Issuebeschreibung drin: Titel mit default zu "Lösung anzeigen"

Stehe selbst nicht sehr hinter dieser Lösung, aber das war vor nem knappen Jahr ein längerer Prozess mit dieser Einigung. Wenn das nun anders gemacht werden (bzw. gar nicht gelöst werden) soll, sollte das nochmal durch nen Konsentprozess durch

**Comment by SimonKoehl** [comment]
Ich kann mich garnicht mehr richtig erinnern .. dabei hab ich das issue geschrieben ^^. Aber ok, du hast sicher Recht! vll auf dem Software planning oder im Lama Meeting

**Comment by kulla** [comment]
For me it seems that we need a concept first before we can implement it...
