### ISSUE TITLE
Creating grouped text exercises process

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#534]
After a user (without permission to approve edits) adds a grouped text exercise to a text exercise group,  they will be redirected to the grouped text exercise that doesn't show the newly created grouped text exercise. So they can't continue to edit it and have to wait until someone approves their edit. We should redirect to the grouped text exercise again

**Comment by Knorrke** [comment]
this also applies to the other redirects introduced in #426, doesn`t it?

**Comment by inyono** [comment]
Probably

**Comment by Knorrke** [comment]
Fixed in new editor integration
