### ISSUE TITLE
feature request: custom ranking for search

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#549]
The math team wants to raise the ranking of some pages. E.g., when searching for "Abitur", the more relevant pages aren't the top results. This is possible by CSE, see https://developers.google.com/custom-search/docs/ranking. We should evaluate if/how we can give them access to that.

**Comment by Knorrke** [comment]
Update: Custom Ranking is only possible using some XML syntax, so it needs some time to get familiar. Access to the CSE is no problem in my opinion.

**Comment by inyono** [comment]
Thanks for looking into it, let's discuss that at our Software Planning tomorrow 👍

**Comment by Knorrke** [comment]
Closing because not requested since 2 years. Open an issue in serlo/serlo.org if still relevant
