### ISSUE TITLE
Docker: doesn't update db if docker-entrypoint-initdb/001-init.sql is changed

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#573]

**Comment by arekkas** [comment]
That can't work because schema changes are not possible that way. :) I think you need to create another sql file, e.g. 002-*.sql

**Comment by inyono** [comment]
Or do something similar to what we have done with vagrant: an command to replace the db. It's annoying currently that you have to go into phpMyAdmin to import the sql file again.

**Comment by arekkas** [comment]
Ok so what I suggested does not work, but with docker it's a breeze to recreate the container, just do `docker ps -a && docker rm -f <id> && docker-compose up`

**Comment by kulla** [comment]
I have done `yarn down:server && yarn start:server` each time I updated the `.sql` file. It worked fine for me. Please reopen this issue if this is important.
