### ISSUE TITLE
Show either horizon or banners

### ISSUE THREAD

**Issue by elbotho** [serlo/athene2#596]
On **content pages** only (for now not on the meta pages) the horizon and the banners should not show at the same time.
Options:
* just use **50% chance** to decide with one to show (easier)
* ~~let them **alternate** (this page: horizon, next page user loads: banners) (more work?)~~

**Comment by Knorrke** [comment]
I think alternating is impossible with caching.

Also only on content pages is a bit tricky, but I'll see what I can do

**Comment by elbotho** [comment]
If thats a problem we could also select a list of pages that should still show both, that would be easier, right?
(My guess is it's less than 10)

**Comment by Knorrke** [comment]
closing as stale. Will probably be implemeneted completely diffferent in the new frontend.
