### ISSUE TITLE
navigation flag "visible:false" on taxonomy breaks breadcrumbs

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2#608]
There is some strange content in the breadcrums: https://de.serlo.org/community/hilfe-bearbeitung/einstieg

hint: this could be an old title of one of the taxonomy elements

**Comment by Knorrke** [comment]
This was caused by setting the flag `visible: false` in the navi backend for the main taxonomy element.

As discussed with @SimonKoehl it's not high priority to fix it, since removing the flag worked. (Although they actually didn't want the element to be shown in the navi...)

**Comment by kulla** [comment]
Actually for me its a feature: I really liked the link to a site like https://de.serlo.org/community/-87993 since it helped me as an editor for navigating the site. Please reopen it, when this is an issue for you @simonkoehl
