### ISSUE TITLE
improve sign up Mail

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2#614]
- Die URL in der Mail sollte als Link formatiert sein.
- Der Betreff der Mail ist noch nicht übersetzt.
- HTTPS anstatt HTTP

**Verbesserungsvorschlag:**
Hallo SimonTestaccount,

Danke für deine Registrierung auf Serlo.

Bitte bestätige deinen Account, indem du auf den folgenden Link klickst:
http://de.serlo.org/auth/activate/075168ef

Serlo wird von einer großen ehrenamtlichen Gemeinschaft aufgebaut. Wir freuen uns, wenn du mit einem Kommentar oder einer Bearbeitung einen Beitrag leistest!

Das Team von Serlo

**Comment by Knorrke** [comment]
closed in #857
