### ISSUE TITLE
Resolve internal link ids to display proper urls

### ISSUE THREAD

**Issue by elbotho** [serlo/athene2#622]
Currently when authors add links they need to use the id of the internal content they want to link to. 
I'm ok with this because it only affects authors (but would opt for adding a better interface for the new editor).

What really is a problem for the users is that they don't know where the link will lead them.
Best practice would be to provide the (resolved) full urls and a title tag.
Would improve **usability** and click through rates.

----

**Example**
Current output:
```<a href="\56561">Saatgut</a>```

What it should look like:
```<a href="nachhaltigkeit/anbau/einstieg-ins-gaertnern/material-platzbedarf" title="Saatgutauswahl auf serlo.org">Saatgut</a>```
(or the absolute link)

----

**Example Screenshot**
![image](https://user-images.githubusercontent.com/1258870/32548992-0235cff4-c488-11e7-942b-cf79fb0784d8.png)

**Comment by inyono** [comment]
plugin for new editor?
