### ISSUE TITLE
improve video injections

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2#623]
As discussed in editorial meeting today, it would be great, if we customize the injection of videos in courses and articles. They look kind a messi atm: https://de.serlo.org/1657

Our suggestions are:
- exclude video description
- exclude licence (if video licence = article/course licence)
- include link under video "zum Video"

**Comment by Knorrke** [comment]
Videos can be embeded with the e.g. youtube link directly in the new editor, if you want to exclude the description etc. Going to close this. Reopen if this is not enough
