### ISSUE TITLE
can't comment on any embedded content

### ISSUE THREAD

**Issue by tobi-60** [serlo/athene2#640]
If a content is embedded, it's not possible to make a comment on it. 

Example: http://serlo.org/57636 (below in the article)

**Comment by Knorrke** [comment]
This happens because we moved the entity comments into a placeholder and render it once in the layout (below the article and horizon). In injections the layout isn't used, so the comments aren't rendererd.

**Comment by kulla** [comment]
I'll close this issue since we rework on the commenting system and thus will have a new logic there. Please reopen a new issue at https://github.com/serlo/comments when this issue is important for you.
