### ISSUE TITLE
Small columns on small screens

### ISSUE THREAD

**Issue by elbotho** [serlo/athene2#671]
This is a follow up for #179 and in my opinion quite **important** since we have so many mobile users.

The real issue is the non-responsive content. 

It would be easy to add media queries and get rid of the extreme columns like this:
![image](https://user-images.githubusercontent.com/1258870/39083410-91f1f2ce-4563-11e8-9219-a0b7e5626e68.png)

BUT! Often this would not work because of authors used them like layout-tables, yikes:
![image](https://user-images.githubusercontent.com/1258870/39083357-3c4b4276-4563-11e8-961e-5d6d7481491e.png)

This would end up jumbling up the content.
@Knorrke any ideas on this? Will the new editor solve this problem?
Have you discussed this already?

**Comment by inyono** [comment]
New editor is responsive by default (columns will shown as rows on tablet and mobile) and could also give a tablet / email preview for authors.

**Comment by kulla** [comment]
This is handled by the new editor and the redesign project.
