### ISSUE TITLE
taxonomy edit - fatal error

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2#724]
I wanted to change the titel of https://de.serlo.org/community/serlo-standorte from "Serlo Standorte" to "Standorte"

error message:

YbN6z1wG/vtLndjDF78YiS0uv0msUMXbDzGXySPyi1xS3TnAuO7gJlDQ7PlzBNuV2vq/NOr9gZCGs+A/ydjrHq6ksJjn6KO1t+MUZfce0lOoYEbla3K50NEJIC74SeW7f836qlvod1ULfFZhbgLh5aEbcoWGPtASLBfB0EQwhArivsKjVXWYTutXh2dGr8CMPq/auIA/XvMDph1VRv7aGoAMvub8pcnObntMVVgMAqj8YLx8wc8qF6UNq1UkVsz0NpF0cfORJJ1EY9MGmnu0YOxpa9+l/TODz88KeMTVOfDLcW5kyhEz9X8+EGH47IHtSb/RcQVNQ4frno03J1USYbsmxxVnTIH+QJbmTSJLvqUEs8nMRke/5F/c/8BVjNvGSxv/XzjLFKgrZEXjmopMRBqvihrLaQWOXEmDpfCTj96JECmlSljatq5XfFmcG1BrQLc1kjSEivUcVXr5IAlKrY626gKiRIteVTkjFbtFQptHKbac33BhXOmfxz+yvwA8wlGHCqHR06Nt5o1ODBDf6U3fq5nengLMULMOPdU9jv9duHH8daAv2RMNqQal3JXbcDoiio6C404l1QGGUw0ht0YE5UXtX1D/JK8F0a+2/yGuhTTg3J4p4Jupq9TCc7Gk/2MjGhdbUFHwYnHrAZ3EAtXxuw/PCV9q3nO1n+DWDqe3/AMQ4mCFaPCEdQjXS0W4lE+G45Dp3laXwUiCdeiZtmf6q+TsUYx+DRe4OHbkavObca8ymcBe0SLsrqhDal+tyI5YEJA5cDk2PuP785t8oIer4TBJp5vdt0L8YVxZpXX4YdqJAp+F1/N0d67GmHl0LTLnDm44THkr/n5N19YVzdqetcDtd+z1c2ubKtN1fAADQ31NHC2Hn8Ze69RfvbT30YHaOvQ76E5gJ144QbQAmXkOtLBqccBiIijtuSSaBth9L9JYbjmEGNqZUvm6j+Su7/xl8cD/qzJxYtzWU4eiJlr4atKp8S9eO4n6BXZ5d2LjucHrUKdEQhn3GELGi1O/J4+kpPloE+XksJGqR2NLwp23NmgdSNnlWPpww8aVJkJHweGQaHkekufWmknEMAF+fjUHI/DXV9RikpsSR9z3VkWUbmv5rPUBNRfZaYSIRMTtD+3Gn5XLuIO/gk9plUVoeYkiIh7k+kySv/kh0hlP97c7MVoqzCYXHqUvvqEbBPs3dET4p54KBtc1Jl0pZNkt1NYkRPtYL+0ojIXErgmoLp7XbMgWXHS53tfH4mZArarRFtk3qLV5LMIJelx0l7q919tJYbRh8k5ekX9+5ZhqaBbY9xTMMKJbyPR65xB2XCqCe5h7pu0iz5jSpBApaLkTCxdZaPNsQ/mmQXmq5p2g6rCw4SR6wT+YfGf5Zh4h3asWqOLfJMFx1Bx6EOcc3ICf41kR71RLB0o/DiqKLYPh58DT9UHDEAL32uytlIxDUs4uKNFgIcsLfslh7v9TyB7DF6gOARNdFRrNlXuZLuJheCn9MvIuG6JBC5Yy2yxJJB43W+FbxqfdsxKW7kSiDR+EfMtLOHYBbqhgT3IVfacHn14AvFB0y6sWXJShUGI8M02mVpPr2CdlaKgT/FTQByDB/B0BJti6MTAJdvQVocc9CmwueltG+C0ombm1FjK5xO9hMkdH5/u+DXCMxcraMasA45yI08H9zzRjYgQ0CVsSpHZl2s5U69kgnXBc2PGYNJER0PvzxPGIFPl8Oe7Wt48UkTA4esuS3Id80cXbMWQn5pXEP0BqztmHxwQ6HZ3mGhlC70TTGY2+EXG4msj7c2R1SLqOTpMaK5kH3pRqlCgzNZms7ucACWbYkd3p9iWs0kQqS2KNqKTajSpivzkB08Cazz6opD7RF9lpsdeOMGgFDvg2FBn/ATXpmMdnL5h2ECmKxLXPWpSSXlYTBf4ZciJyu8zO9MBofC68+CMHdyn0w5V3mVl0FfhfD6SMGnZ7gMFmCjrVJ9apj5aN4GDC8DehaH1qKrHDjtLv3Q4f275epO4NtFLRZ/EKlSWMl2kR3YiGh1IqMYiJZcizQYVWUfkFdO88HNInc5os/UMk+OpMlvDmxohkrykVoW4FzIKND2NC0jK53pDAlwTIhDpqEeuTEw9lxvgYzQ/GTvzHx2tJtEgW8533KlRz3C+3bm0Lw5lAIAbkk6Va/nGnHX7bo5SLiK7aAWGT24Z95MrCug/GFQZj7F1S5clrE3o1oJ3kO8Lvn0oth/ShLzWfxYX6xS4NYD9X3+ctYXM04LmTgqcv+6UJIN67JlpIX1MO/CZQR/5JSOd11O6hDUtKFzaNi++KRFQMSzhrUZcg5h2AEL2rDlYZ/Pg/12Lr5GoMXZdO2oFODRYv+N0+TQjrC0bGzrtPFt54JSc3TK1jXi3+9w5QOvLueCvqoJozftXhYb6mVK6+vDInaIFqxxqpWAv/rini8kqQdiTeJGs4ctRJRU2p7BhMd1Lugm1hEgEjJ68Rn3c2R7MNcG7R9yDRIg4wAa3hPB9IiSlfeyU1IMLRLBjEV+zMma5BoSBPFJA7+9IJR/cZVPoInFHyfdMoLASNmId2M08zDMLwGXwCqcf8rrORle7QVXOX985xtf4pqdVNEy2ximSrFEFbOBMOjK3I9/JVq1JH/2XPI3LBcDwclZh1RxVXJBFkPlAjnn17gDF7MdKyVH3KfTO5sDWrMtXF6itWhDs2M0oh8Depw4vyHmdM7IRrbh/Fgzk5nX2ksP/kgPn0dXbn+2CLhNyXKsWwtWbxTLw8ri8ha1EQe8EeFwoi1yPzhQJM5rUBFXnG0KT3A1aUtgaPiCViHfYSKp+usBiZVe9doNIL/4y/9xoPAYRRbd6aN51jZr7gZYMrMVFnjyp0/SLAC8Ra1Q/flYlqPDbakQRyqncjCTKkyWU57ypUmxARu0l939a5tZ1oQtGW2jxRvzSwUXf+MWldDAUGIakgTBY1irceMEtwMvireRybsW+Ooe5mgJ/EqmTc1vKGov8buKhnfOS+XGmrNZqaoE9sgyEUj4wLSxUiOYjHcuK3tzzYU0ZmDuzS1bZd9pi/z60a4c6Z4dgNDmIobL2xK/FIEtrG0c9viJzPvS7iJtwJO+Ry6MOJndTuXg1tNgEzOzY0s8Yg94T7LKNn/ferdJLEL7/17LJ2o8bz1DLNs7bw1vmOPAH6Ebw0wZbNNUnCUXdE9aHHc6K8qD8I6PQu0u/xqGI5cYfaX/f6KHVxO9wb2j1OBjJvlLJsOnSrnVMokiDWDClamPo5Rb5EXbG3QRsfvhdqggNMzvI+fmWjwoe0VmBzNESDP5SBGyorZsCtFppAVXFiAqEjCcICBSRiFqjxtYg4URBvFwu0W9fbhcU10ShaPHBE/W03L70j78izI8YEyjcK6VdGYAFD3kp2+Zu2qnnc1Gb27Ru53ZWRSTmZtPzI9wl/u92dQxFEKEPT8+1UU5pK+oxPLcdVIxByc8wDfNe4y5oom3rRBGRHxxmyjmcDMIRas8hp09QibJoO6anSuawb142Mvx1E/MURnn5x2QofvNL5U8dHpIM/CJIu7tLMrGaBL/H9HrulUbjBFGOV+DS2bQkC/GaPBss4oaqf6/JPD7pbNWTDnothf+kEyZC9q6xzX2WlnsCCUhHg5hUELrh6ppnx0IwArgtyzKDmDYgxfppnep+JMo533GQOoiY6PfRPHmgevgI0ZdSVP6+CFl1e7c3xtRDQiEqHVJ7+UtKpRnd+osVo6SbvF6mZ7fdBuKqKGTNItEwsmjhN5FRm/o0CqO39jmno1ZgCTjtZmwUJn5ljyLaP4lWp6okHQuQwS2464k8E/6u40WUuyEZ7bGb0T1555laltOhl0pFUkIhnl4xoVmLFPwWLeZXCjhw9fpd1gdqRParVDm6mNWw/y0z/dL4tb5yrUk2I5QE4BVuAArgBQxQmrHkh1qCn+rv4UmzTsdb1KZxoLcDUnSUdcJyAUtbbbQLNHJj+PaSG9DaoX6mDmLiWr06lhFDsHs+qdjP7fAwKm5q2INPhbGLNCfuRaEINOz6cnMEW1p+hFuLOc0Pzt1NMR45Sv+NgHU8TzNgSYbC9uz193D+FWHClMuzFn5mBdr04qnwNKNIhM8GXJcJOC4EXlFDhelwgZVES5Tu/4lN+Q8H0K5fl36c6pyrHu02Z892P3xMSv0I5fshH2VnR+hZgNAvVyNSgrof0qANOKKUUUVR338liPVg0mN7rBX6SUxfkeHLxZVmxZzci+H5ZRQVOOi+xLhxMvxvpcW6Zliw7r21gKaELCFHIp9g3Ho3F2gcaAEOAVwIH6YsrH44h6L+K4EilWNQUykw9tFzR5hxZ7oGElXAdtUwZoUpHLd8Mq/qgyXEKitS5uOVUij3jpqQt60kU5dKHs7KkRPQo3sfakIVdl3VQGsFSwHiZNTPc63QBOltCn1ADV+XDMlwUkpjYs+uULK+rKZMtEIpFaFPz73DtukEoSPZ6maT7tZkqV1yY/PY8UbhVlOz42KEu/fo8oONIhL1QyIyE7NPzKgqj55AuLSlBx7y2V8WLgqdJP7eDELluijHSNfluV4Apd+v04bLV8/MFzoUe/1AkpfSBQtBij/xz2VYtd2N2juL1cxiKbTrpIF+diz1YlE3K/3V9dbMYcYK/bU81gxa4P/Y86XWyuNr2VpfdMX6QgKEef19O+SX+2rgMBrRUdhFoqLGl81E5KqMZ96+nB+HKsnYPIkTp3chhk/m/bLrrdy38/RZeGkpTV70LDbwtipj1ctVwjKgmV/ycO7TLJeh1cTU8+ehCEIE0CiTW9m3TqfrGb4dvBv1ia+lLOSmu6QSao8VXMR72ajHeo60NUV7EWEUsnC3Icu2miSIT8r9SFRvwdXlN9vdZuIYRoywC7qghhYJpY0ufycjEImxAitF0odQ9pLT7ibMqacMZq4BYIUOpTJrN+RzMxQo+H2V404OjjXj3r6iTaPQNQ/IlqT5owSdAO8dETVnk78JWe5/mFH/2WFeizjTyKHGvaDjH1lUy8iYdxjWPV51QaUgOAXxwvYzgS+oVo5NpXCBkKoOq0yEfVlLjhdsuT5SJk8+Y2P5F2h2QHWBrteEHALchPOhDF3akafIPyaROhBs1SODqsqDyPKSL//wpR7f6ZWNKIvn1+T7S7vqqvzVYUig9hTXprC7HXmSuBgBnIAgqaxr4DDb6xWZS2abv/3e3USlfIMN21rVeyCKILifTWrLcouxOJ/D5Xfw2uHq6wCI7DogsupeqLYywMfoipzTiieo6rC5gkLaT+aGbioEigDUXLdb+Q7KG2kXBJHX3ZVFTY1UEyrb+1VFX2SfK6H50sH1LEMAIxn5bjfxpphmPkJvgatAOVXI2pU25LHvjxQhtby7RRf4TR0EUCRdxRgqCLWlQhqDaLxsUis8Xy5axxWbBgq8BTczIVpjz6zgPYxOr6TOAwlY4AJ4CxfzudCJj9ZXV2HxUEfdgtg4eZzQx0YDKExU/Er5myoHHniPh6BzL22Vpvxe6R7ek+04h5yv7hiX+5MsgwhHa3TVawxnTjnTBmY6zi0mbLOJa+m73v99BUaNTKQhAIRzPHuVj3sNkaVczJDkP1+QalVET606peqlkc6nEsoWgbJpfdZre+tVxIho0BZlTbEYtlhd44jCLstAJy6nhH9zvio5u5SJ7xQkiYl2X8vp23uvj+lLPIlr07ohgEHnoFQ2WK2otlrQxrfs2RUC4/c4OdVuWL4uw4YoRfoPkPpxEa66fHcoTn4YSuBElzeY5WMCTJcVDVhZ+QSGPHvoDCC9dKMmRHv/6uRXE4udBfoUj4XXxFSVUzr80EC4ET9ZeG19+cpHauHz0YEwDSUploEAJBi2BkD86joHuuNO/pNJp+ka/ltyJ2KmU9aTviLizGleNdaJrocbWmM5LYDWNNgfeeHgumWCFS0FWTyZZYybL24OqCGzx5zkmX8vAI1pfvb1MFO03XMQRKv81QEE10BKhfPsXjvR+IsAni8x1OPRaZnn4Y1I1fIoG4kfzrImTp2dLX1vPplQ4SURMWiLPciE9on32RwJa8SHjE6LJq95l6vqwiNFQCH0UwouYhEr/v18/xH/+UuCvHdyZwOPtBNgIZNEsNK+IbBOSLfh1GeiXmtOKdvyD2IpTanCqRQ+zB9GUJshsBgvcuSYmpQmVMUZqGDnqI73d9cw6jtpOjxGk/gSIx+TFPxceQ3GWHzf2sQBGZLyUl9pvujp0qzCnMhrAICCWefDa4ScjDIyGbaUcMRu+5pP0/vXtHAsj+3Dmk0vokSnqD2+tiny4kNmOLtFwgK5os6Gg9d4r5GQEoXz3ws7c+1BZJCAcw1RQ+DiKE396scjBBF9waa8WPQH1f3qZes+3LHXRd5hPDFa3MuO6mcacUlJ6ADvXK+YQZuTDszR9XkyEytzI9D8XB962PdhqTrYfBLH8UhxDr5gKd32jSIhiunAEjV5Qh1nEQNKl+2CaDNm+/VdWLiGbbIv1OWxvcNRmLr7aEuo3UgSb9ILE0xTMLbZDptNCPJIzxKjAykUMJpwkDRphYHUVI2+6j0IxOtNuP1JE8P1obETXBWU3TgOkYR8khRtM6ksYmDmp9dA+m2U84DMaFFDbnlsJYtCifZYfMb+mIXp0AchNmRB/vsgDtFR7si4U+mdAfnvKoARmHSD9Gkkq46ozD1xutYTz8WD5O4VIk8Y7K1/RcGuY8Rhg8kn96MEhI1jFiP5SCvQWmYT0YyV2ZJhJBKW2IaVBWKbUEtW4+otzFpPdNioAsSH9Qn//uvzrPM6Io2H4mZaINmbgLp/M96YexYcJrtOPWQx4kyx6Anu/8h7wCsxWg7QJs6Et8A33ZGKklLL7pTD5rOYFES3pMJwmAdijqXE3KCWhk1lylzIiwUanoa9KUG2G5M+RYcczBgWA6hdqkde5gkzFUl4gnLCrjFgYiYyMmT3bhh8zDWWvhdJD5ygkpCmN6QnEXDAzoLuKR9zjOf/ld/Y6Ctlr4He28YlGnIp3Ts2DhGCEhEocFxe8/NmExKUrlrTMN9uHFHPYy1CNo5mSqWIBuz12QqOeKPcv+hJM6fiSKgpdJdikMSKtJHfivBOIaobljuhueVUbxzlyk2IyeCNJDxUMTjFn/rR2gPrNAc51Y4GUnpfblHpGjSwt3ugq1knMI3tuyaROAIY+IG4jFEHsis+wlUgGl5lRO4ertEwJWVNtEqTiJGGD2gDduoDeWVq7zHp8xLfKKv3VTovvpSG8yfD6rhJQNfFGzbTe6U8rt4LEUME9wzLOhNK+0Yejiwk0H8yFXbjuXqHBM+Fbpdw97tql4Yir8IrR3RWuZX6rT/5tGuUVGz+7qqYC/3dhRTn/DWv/gu6gyNVS08Sqr18J2EbrH1rcw4YOoVx8tXoNxZHzB+KkbEbnPiohgDNwwZrT3VCF4CfMaIwcyfXzfVjKupQX4IQEl2/EkZKG8o/MemHfdsOZn998zwy0ITwKr2mRK8lRdtpHAZipguTyB3g7Ke7Zc5n1kVQ1Ptssy1keyNgvFUYNai6aWNYqZ9KZtVO9kFP1hhDkE2ocDwEt4gRTi5sNlWw0+7ipKuf1a4Zq/WpLfcHys/j5RhfOak7y6Xp7/5y+8UbtCMB9LMjyXqV2Dfgu++/NDhu2704fgcqrFMZ+Dvowusc1luy/7J/FjIq62JOZAh/1a05lrfKZXV5+9WHSXn8hw6v+7acezNLC8t6F+XxMn2eQSZVOf12FMo0IgNme4pAFO8RBFyU8eSt+qLTb1KK+WB0IrRwhfIJN/I+DeSqucXfwIVpcVJ3cbJOVITeXR72Qt1OFehsVpU/1pwoiuJxzoDsAwiwKKC7QhKHoBcQakMRxttfn7Iwj27+4C5DlH86W1taWdffBOVrwBMgfbyL+Xwc7aomYcmceZkDOFf13lfXb5gtts2VIDMRkPd3/phKcnsLTFrdfab6f00QrYddJpz1hjI725PwKJy2IDZ7ke6TK1CiBFqkqRERYrA/ztEeNSqWWZjJ32MB/fSpFHCpkzDCv1xmrIXB5Jq4WNRVnfOdgfNbmlb+Neo8b41xl/KZi10aZtBjiyO3mnkg/tGwDhTh8lXvc+J2nqe3ovBLFpynaddVWs0dLs8wC3ZKUtMhSgN7aNBcwyJSUmUc69MkI+Rwt382eYAQ6GSkaM5/O1lFjBOmN3bUtNAiDXSyM7fjG1DYSjGwZCJkM7YRqzD3gSHpQIBxA1jMh3oBatqhOZ3WGSb9wXUE9bU5ZqKW4Ao080i4h03XeQaVON0nTvjuYjgZXOAnBo7UuYiNnby9xFToeYfJ5fQp7OStRSiQf9jxx4skCaZq1NYiL4uuwRYzv8gF+POJ5kKqNRh5hwPTUfkAah8h9i/GKXBFDi9V6Em6//fr3ruaWGkO5uFH+JfquHk4xhbAeKbBaGZolqme/oDwyA61zYkoJPx8l7kYpn8hMtt3prV91e7lVsuo8Up63hMa247ks2MunmddH8pTvYcC70G1eliOpK96jTWQVsldTjMMI/OoHcHjgGmpxfmCIRMYhJ3QWkqLJY+OuXVOcTVUuYeDYadJMN0XCR4aOHBPiBcp9yAQnDsnh95CzrCBAgw+577hYabqAL8UIPPGJeSETZy1GHBChzwgdtAiMLiH3kmCNrLNhdAuK7l/Uy5ejQN4c4857ssQRIKuIoKsXT9bsix93LTmJ3LUNQMWlxnnukFkScWklGN5nJgsNIsFmnhOWyvjRydCQlOwAoutGVGLRAqt07XOaHhFgIsIscIbVdQO/yzoKh0Km8BSuTr7Po3IXkfBr7BSTfk4S0VsX3ldVu6Du9ZV90QhOxWNlw7i3oTyqO/Obubp387pWE0e+mNs8vlbOMJqmhRI/W18FE4QQ60xLV3zcmGrxD9LAZfTNszfbHHOCqSIJRT0E4nPi32uRhjdes4ybKQdY2KLUKtUWevyzjl3vNL/LKAiN1aRLrROfzFrmv9UuAuj8JSuP2Hm4K9zoWihShlFbB1kqdtqciSmGI2Y5CDFyaSOeQ1zM8ZCZB7PdXMBdsujpKp9d8zGgSVgBokwjaOVqisLZlr1SEeavPqvupymQFWJHZXKfsbVdLdknUZLYgqN95EX/o78e42hRJdrJsRNySrlnsiaQJPE1xKFf+LqfRP6cHLgFYoubO8vvo5MT26kXvXFcmSlwBU1RTT0FiOw6D5CktBwMH5iQjHxVN263AXpPCyLrpjE0AMcUpQHJe51qfqOYuc4hkeXbWybCrEOW77qVRVVnpzAas5jn/h/Xk4Xb4XT0t4HBPbbnoW8bumpz/KPpMbfz2NRx91FmA0O4Cr8WPox7k+yimbYgM5QvfzaOgGF+RfDEq2SuR1eM821ddeVcLOAsUUH9diHvpdrkoq9PgV8NaA4oxSzpev36Lubr+wP/UOKPlomH0fKCAKxgNzDY71C1qXww7+0pAO+gFrC6kUj7SbOEnNZ5XzXcckVc2OzW6Lv9hm/yDZ+SBwx5rtLfPY5853x/4uS6r7YyxYyzdcCnoew5Xen0bU//vyaabGtyBBJphh7cwG/US0vINA5/KpWWTU08p0L2UZpBZGyZ8K9ej/LVmWo8grhxtPSij+xw5zEetYJ8lT4wZM+YLJqOGBQ6M7PN0UK6O1LhhMrtqPSxohJ2y0xppDUKM1hM7mnp8OCVb8uPSvWAb3I9CTOtDf1cYAsa5D9VTnuaKWPXEH0PYQtoKHsyQ8p2b0Gt/41WzxfYh1nzEBN/yoDmik+xRFi7HUoOSCWHhK2yyrk4jzRdDhFBEvuFoFMx8Ntkpn6rB+FY4YCYKC7wRY+PHFq72voKEsv0p1Z7n8dNLSGsLvcwluEkOYCX6/95zlW0v/p5p50CoPjHbcCtVkkBvZLgcaKXye9tkDBnSd89fOnHxNPiuNce+zuXR1Tk6O2vIyxBOeYC8ZUBD9LKVp1P54r0Kj3z4FgT/Jmeqj5WUDyj6HaLSP9PRrIdbSnH22xPv1x+O8AhEmykcPOt92ra3zkJohIZDhAx8QMNUfhqrB7TECOod4i1WBG/kOl5aut7RcdsLGK3DjmQBW4dNsdfpb9CvZqsggfUjpzRfv3q7khN1WQIHGLOl3jxBbDu/rxa0PyYh28p0xa+g8ENS2ev3LSlAkwB4ffRW9zmJI+5y15UdeM8/vyO4QuZMDxlHh+ZylhhrZd38KpyRT7eg84xcXrz59kvRGhiHyXoq2BWdsD0PGbHP/8jlx/MG+gAnqzoVe8fAmdbB7KQcRY50llKPIIlzBy9XhejhVFDmChmz1jEdOLWDgp1ryKQ7+PSenv4gP4ER0yyTm7r7ElWQ0uAYZytgauxROT686AElDKrezA0M8vM+8k+14Ll03YaOX8ClHCQFvBLiN2JdqBUQ8nE0mj4odOcVhi5r3CeDkGLjqXJLK7CyaXjMcQdPR5QGgJgkCnW7Te/QZ7cPAMh9NTYuYmhCPjMD4hn1RRIKCuCXAlRZnvLZVSiPzuzud0ll6a4WQom0Ntn4CPtU67Ub0XvAmdKxRUGF9lCkZH56eNcd/tdh5h6FfkiZ/5KqgMubULeY+bZwrfOF+EdITLZu5qzTt1tRRP9usaKvW4F4bgdw90981IDZz/KuGv8dYzurdFrcQmqO0JxcTdJa57bqYHVNNDL8U6mdWIfhVQwXMU8+L4GqelofBKR3oeCQwMcNo5p8dk4AyO3MOyUuT2btR1DM62fQqV7hqYHuUx7rNozgHi97eUBE/54jaUPmRsrPLRWaklH366Z4stAsRyJN2uZ0J9Cu951wDvc2PmBcp1+O7aEhjvePSOGPoBRVp6XtohSfwDawc8hROlcXJXoam4Sl2lWk4ZTc/wryEtR76/MjtJc0szkX9KNerzlV20w/jMY1GTxPxvOoFNhpzH0XyJoQmenfyhcBn2umsfKzNyrlgP7SljnkrGPihu/VJV2iJzK/qFOSkof4lQunx8L8fI3XJlZZPZbWJIVIgXhDlTW9ujJ+75b3Z0l7levkMiyCNLCyS9xrBBoAITZtGfA0w1g5BfcXTfQib/TxRos/ChbX7aU4B2VQO/mp70tUJpIQV0dILCTzdFlJX6V/20nuL+oZte+gtlJT3+BZP71wcCwTVRqnF/XWvSldgscqMnXz453V7wyRhIhmvI7VzG7M6lwH1QwuWTgiisEaXTwoqRB2a+zukCAu7BROc9pjF8wDSASZpAkIOZ8FxD0KOpIAF8rWA+I1xfDrCOtuWRlZ+uEyoUAjJlfpMeu/Aw4ykcLIlIcFHw5isE1HBKMo/Q6eFrPBizeuHot4CF8HpYLh+ydpiiyHhd4GHaTeIDxsMITtP0gyGtFz7eeO9/T4go92Lq3dJe2+DCAwmGePeJ8lW3p5JYRpmJEsXcJxgRUswW2g7oYvDgLhQ49fgMUBbNw9TBKj6kTdNO1JNNoQwZRtPNeRQuuxUsIZ+AFCXQjT5tNZ4li4vLIT1azFYNMKZuKWJACuk6xbcV3bs3UAbV8L9oM8TZtAFeV/ssQEUxX8w35MCACSKGpk8Wr+qSb/grb30wbfmPf0M3zjx4iKBAOSU/C2CCHrELAaMZQtYhNmlhdzUf6qjjCTH/XNbQTpvLZW2xKEYykS7YwGJ813o69Nb1l1L7Z+SrkejM/LGAbVlCteCEun8Zl01SjyO1fw4Y9+7zbVrzvsVDI8IqI19FXBQL9bISTTxF6oA3SlT6Moj1iJIS5vEXDL27EVeCkDuBaKFPgAQI0ZHI2vBfPRpEsiQVEYNJ83pAMCnzR7TkG1RH8fhAyRZYL9SntdB6hhqwNbc5RpHTDHafp9RfRMn8tar1lc2DDNsbhHxV4lXOunwR9QAMw+lhRT/VvkCKPYIsU6w7XEvp39O9hLQYlUhLPT7wcLdR3c6dYwN+IXrXpUo+TsxoWwAF7lLoR7HGL5fJYse+Di6kkAwuSLpjCArrWB8sDqBPAGrIOHLI/gHvzCJuH8Lz7rM5nlxVynrtBERrDL/Vo4ickWSs3ZwJ7GnxjVv4csZF103t8vqdxdm5MAn1A5+8lm5IXnK0KDkJxMgoTTzrn1SZWUBhvbZK+UHETXniWXMZxxZU5I6chnBcoEjA7/mmAsn6YbZrumhuquWzQCTtJdol8GBpUxDKNMm/4t6p9BA2tk9pYTIRfyQfoiUc4ymO2V/afFIQkwpBbxOxS/sJjQhY54SgCxN/+erIjyjxuDNk0nr1T062YnwHHxa7b8S1qARKPj5XjYHuJKdhOIPuDIeLwsIzrJnfl8UC0zZ7OEi2q1oEURRXDKAIhI2iIKW4/fbKl9868f/o1fMvRB2s2bRBJPzEbLAUm2zsudLqkwgJWk1MWGugHurZvE6ZW3EjR9ZmcCW2xihc8TCrg/OCo3AmIIXrZi8Pw/r0+N7eBx2o//UJlYeBXvqrm+ag3z1iIJrVm83C2ByJGNYv+CQ/qOeYKjAQWOYcWP3NlrMl5iXqjVVTEUW7aaYY3g6rFKG0UNy5Ajha2IEgaWXhxXurbB/zPQWVXefdtbmpJlBqH2khvKo3XQSrmGMpDjJFaVwlr3OqSfdRf0kCIqaOt/dK8kt1WpnOOEoGF2Ley/1XeMyQWZua1MsGVqrG5Bgjv3PQNnUs31qoFjrC87YqsDJtAEM1CnncUoTrsm1dK4xcibeZNUAhu6KbmXjlluuf5zRU/sfqMxttEU+GO3mCMVd3uxiATcUhaBYU80SWhTWe/EdHqIA6PPqUd1UDc2wEB4U5pgQ4lQK6U6GvO2VczKycsblkW98XOR7yFpm5GreLTsICVJaxna4BAJhkmNpql3KBW5b+N51tDQloNnK28GD49WLn/0t89FT/qC6mabR5skulSnpPx1aHlshreZ0RWsNCMBnRYFC1U5kTBXeiQBKLeUEZf5DKH1mVo28agH1jhCpwJogjcEx/e3Y6AQR1zONLQQFpWwmlrE1K7St7YWxZZiLRvb0HoveWJlXgJiREjjr3Q9otEqueWdfMKwH61IXAbBbY/1oPBRq+eUdHf95RCMGYPSg7a47jsbAfhAJpS4cigLXRvbFe766S4akirxkrktRfe4GqZR3lWBtiu85QyAQ1PSA2QCmPC+XrJDBjuVzfJI3t0P5fSE2R6U0yYrsupxXePp0y1JZLE1tQrXgx8gKkqOK3akPAij2QivsMInp8DKNX6Y6O1+mU2YGYALa7kixbCenvWfzfegN5pAif0QaKCPtUW0ph7dgEdBH6zTAIHRfUdmGstoIS8115MOF7eOQg+KE4iuiUzKedHB/hm/dSby7WBZrErujcvBIlORV7hcnjLh3p4GXu5J6ZaV0tC4w7brFF1b10QHOwG1FCxgoDpUdEugUwJ1rIJOmYTcoQcGSX30zktcwkNC8osjdYeTv9IK3eMCGjLY2pTSlb2QaK5zxwuFcri1QUlbDdng/6g66Y7ALfjGgtjexJ2kjFFyev5rLnPM+X2z+FHcq6RJpqLzyLg4uGhkPdMIb8hHdRGLB31TrgfAD9nt3/7wO2T0wzbNjQg2imQXkMInh7+N7OrI+CFh0bHSlP2qrzN6aMwemOxgZw60SerPdiYPj/PZrPnvgkiadjSzUfeoV7UYExSib0tFdeP2Fu4IeiDZgDK7p4CLP5F0PMXKm1PC7lwwu5CCYra3Yc2zQg8NV7+X+O0a1uRWjhVPzWQYOaaQ27OcQoCYwYudyVdv7e7ZCVtRaWzJPZ8KVvYbYSg8/wF41lJPul+5yxhGw/hCGtQrULfQOIvvzKlYdXngO0BNdWdkSiHSLBGAXtKjs3xei6FMeInZtVLiGVvDktSYykuSQGkCvDnvnLHWiwS5VuOC2GwIq880CDXcovdzGdcEdZ1uYVwM1syz40heeFvdrCghJ9NOPmO21k5AzNk74qHYm7WULmJDdCz62dWUJ20h3m65YGe3l6bGoob0ChK3virtHqpKWEa7ksvGzXG8M1ENLOdrgonAsBKGQ1OtiGtfCgDiLp1KpY8nxZWnkAOG7k9MORrfiStUKT4tMuiPUQS3e1OpG/5fH9fQpyaFwHgv1LUjxP0jtAUoFtbc1lpxiRCYZ9HjyGM0Bfhw4sNupoP0bnM9ePu7cAQvmts0XGO2djEypVdP1eTrr8GUMO6xrg7EocuynG4etyLWNtggv6bbd3CBZH2n9oJUFQQIGJiaItJfiiD0O6130n3UaAScXMA9J5T5yZEkgLrBj5bZ2uaqSjCE2WsZbevP2TYaZbs7jOJ

**Comment by inyono** [comment]
```
Datei:
/var/www/athene2/src/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66
Nachricht:
An exception occurred while executing 'UPDATE term_taxonomy SET weight = ?, term_id = ? WHERE id = ?' with params ["7", 2719, 111264]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2719-87993' for key 'uq_term_taxonomy_unique'
```

**Comment by inyono** [comment]
I suppose there is a bug in the taxonomy edit logic... somehow, while renaming the taxonomy element, the system tried to insert a new term-parent relation (which there may be only one per term and parent).

**Comment by inyono** [comment]
That's weird, though, since we have `UPDATE`, not `INSERT`. I'll check the database...

**Comment by inyono** [comment]
Okay, found the problem here: In the database, there is already an relation with id `111264` from term `2720` to parent `87993`. What the statement tried to do (not sure why) is to update that id `111264` but with the wrong term id `2719` (off by 1). So there might be an calculation error somewhere in the update logic.
