### ISSUE TITLE
wrong styling on first level in subject

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#783]
Edit tools are not in "participate" green. But somehow only on [first level](https://de.serlo.org/mathe/5)

<img width="1257" alt="screenshot 2018-10-30 at 04 02 59" src="https://user-images.githubusercontent.com/1508477/47693141-bcc1f400-dbf8-11e8-8618-9f93f2c62f65.png">

**Comment by kulla** [comment]
Is handled by the new frontend
