### ISSUE TITLE
Double escaping for umlauts in site title

### ISSUE THREAD

**Issue by kulla** [serlo/athene2#787]
See https://de.serlo.org/community with the page title `Startseite für AutorInnen`. Title says:

![screenshot from 2018-11-01 16-54-38](https://user-images.githubusercontent.com/1327215/47863334-52c36d80-ddf7-11e8-85e4-b263eea2479f.png)

The reason is that the `&` of `&uuml;` got escaped:

    <title>Startseite f&amp;uuml;r AutorInnen » Serlo.org</title>

**Comment by inyono** [comment]
Probably related to #729. Since we now escape titles and stuff, we probably now have a double escape somewhere.
