### ISSUE TITLE
Registration on de.serlo.org failed

### ISSUE THREAD

**Issue by max-herzog** [serlo/athene2#848]
I just tried to register to the Serlo Page https://de.serlo.org/user/register and failed.
I filled in all neccessary registration infos. When hitting "Registieren" and identifying as an Human via reCAPTCHA nothing happened. Tried it several times. I have not received any corresponding email, etc.
I am using Firefox as browser.

**Comment by inyono** [comment]
Fixed (https://github.com/serlo/athene2/compare/1b692ede0be0a1e2cca8b609f26a71a8c3cd3175..709b0344e397447481936764da5550df4ddc6419)

Btw: these are the kind of issues where spamming #meta-dev is fine and encouraged 😅
