### ISSUE TITLE
Mail: Send multiple onboarding emails timed after signup

### ISSUE THREAD

**Issue by Knorrke** [serlo/athene2#850]
1 day after signup first mail, 2 days after signup next mail etc.

**Comment by inyono** [comment]
Isn't that exactly what MailChimp is / should be doing?

**Comment by Knorrke** [comment]
Don't know, is MailChimp automated for that?

**Comment by inyono** [comment]
AFAIK yes, typical use case of "onboarding" mails in newsletters

**Comment by Knorrke** [comment]
We will open a new issue, when we have a concrete concept for this.
