### ISSUE TITLE
No left sidbar menu when creating a new topic

### ISSUE THREAD

**Issue by kulla** [serlo/athene2#854]
After creating a new topic ( https://de.serlo.org/informatik/baustelle/internet-dinge/bevor-los-geht/129537 ) the left sidebar menu is not shown (maybe because this topic has no linked article or course?!):

![screenshot from 2019-01-24 20-02-02](https://user-images.githubusercontent.com/1327215/51702311-c7cbcb00-2013-11e9-942b-8943deacdcd6.png)

**Comment by inyono** [comment]
Navigation get's cached, so it might take a while until it's there for new taxonomy elements. It's already working for this specific topic ;)
