### ISSUE TITLE
Concretize license page for quotes

### ISSUE THREAD

**Issue by kulla** [serlo/athene2#875]
Our CC-BY-SA license doesn't apply for quotes. Thus we shall add at https://de.serlo.org/license/detail/1 with a sentence like: "Die CC-BY-SA 4.0 Lizenz gilt nicht für zitierte Inhalte Dritte. Diese dürfen sie nur im Rahmen des Zitatsrechts weiterverwenden"

This is just a proposal / reminder for an addition. We need to discuss whether and how we want to change our license page. This issue has low priority.

**Comment by Knorrke** [comment]
The licenses can be changed by `langadmins` through our backend: https://de.serlo.org/license/manage. So you can ask in the admin channel on discord for help. I'll leave this issue open for the discussions. Please close it when you found a good wording.
