### ISSUE TITLE
Stay within curriculum taxonomy

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2#893]
If user comes from curriculum taxonomy they should stay in curriculum taxonomy.

Open questions
- how to handle links to content within the same curriculum?

**Comment by Knorrke** [comment]
Duplicate of #531

**Comment by simonkoehl** [comment]
Danke für den Hinweis @Knorrke ! Habe #531 stattdessen dem Product Managemet Board hinzugefügt
