### ISSUE TITLE
Review timezone settings

### ISSUE THREAD

**Issue by inyono** [serlo/athene2#902]
When starting a discussion, it always shows the time as "2 hours ago". Probably, we aren't using the timezone correctly (note that we are UTC +2).

**Comment by inyono** [comment]
@Knorrke: "Seems like we save times as UTC but interpret them as UTC + 2". Things to look at: `timeAgo` view helper and datetime fields in forms.

**Comment by Knorrke** [comment]
actually, duplicate of #457^^

**Comment by inyono** [comment]
“3 years ago” wtf

**Comment by Knorrke** [comment]
No no that must be a wrong timestamp :sweat_smile:
