### ISSUE TITLE
Silence the console

### ISSUE THREAD

**Issue by elbotho** [serlo/athene2#906]
If I open an article I get quite some output in the console. Could we silence that a bit? :)

- [ ] Some problem with `font-src` syntax (Mathjax I guess)
- [ ] athene assets output, do we need that for debug?
- [ ] maybe real problem with hotjar?

[Example](https://de.serlo.org/mathe/zahlen-groessen/prozent-zinsrechnung/prozentrechnung-mittels-formeln)
```
Unrecognized Content-Security-Policy directive 'font-src:'.
---
########################
# athene2-assets@4.0.0 #
########################
---
Uncaught ReferenceError: hj is not defined
    at window.hjBootstrap (hotjar.js:120)
    at Object.50 (hotjar.js:120)
    at n (hotjar.js:120)
    at hotjar.js:120
    at hotjar.js:120
---
Refused to load the font 'about:blank' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-inline' 'unsafe-eval'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by elbotho** [comment]
*mathjax*
do these still appear with the editor a new version of mathjax?

**Comment by Knorrke** [comment]
Second one is for sentry iirc. Hotjar error is thrown in the hotjar file itself, so we cant really do anything there. Thought thats caused by adblock or similar, but havent checked further.


Whats the mathjax issue?

**Comment by elbotho** [comment]
just a guess that the first and last message have to do with mathjax, but no idea where that is happening and did not find any references.

**Comment by Knorrke** [comment]
I opened #907 for hotjar, see #908 for the fix.

**Comment by inyono** [comment]
- First is for debugging purposes. Makes it easy to check what version of athene2-assets is being used.
- Unrecognized Content-Security-Policy "font-src" is a bug in the server config somewhere (I think Varnish?) that we didn't fix yet.

> do these still appear with the editor a new version of mathjax?
Not sure what you mean

**Comment by elbotho** [comment]
right so together with #475 now all seems to be tracked.
